# Generated by Django 5.1.4 on 2024-12-08 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_app_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='example1',
            options={'verbose_name': 'Переназвали модель'},
        ),
        migrations.RenameField(
            model_name='example1',
            old_name='done',
            new_name='aga',
        ),
    ]
