# Generated by Django 5.1.4 on 2024-12-10 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_app_list', '0002_alter_example1_options_rename_done_example1_aga'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='example1',
            options={'ordering': ('id',), 'verbose_name': 'Переназвали модель'},
        ),
    ]
