# Generated by Django 5.1.4 on 2024-12-10 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app_list', '0003_alter_example1_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='example1',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
